version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

  technitium-dns-server:
    image: technitium/dns-server
    container_name: technitium-dns-server
    restart: always
    volumes:
      - technitium_data:/etc/technitium/dns-server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:5380/tcp"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    deploy:
      replicas: 3  # Run on all nodes

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=<PASSWORD>
      - TZ=Etc/UTC
    volumes:
      - code_server_data:/home/coder
    user: "1000:1000"
    deploy:
      placement:
        constraints: [node.role == worker]  # Run on the manager node only
      replicas: 1

volumes:
  portainer_data:
  technitium_data:
  code_server_data:
