services:
  input:
    build: ./Input
    expose:
      - "5252"

  aggregator:
    build: ./Aggregator
    expose:
      - "5252"

  stats:
    build: ./Statistics
    expose:
      - "5252"

  unit:
    build: ./Unit-Converter
    expose:
      - "5252"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - input
      - aggregator
      - stats
      - unit

  redis:
    image: "redis"
    ports:
      - "6379:6379"